.TH AZBASHENUM "22" "October 2022" "Neofetch 0.0.1" "User Commands"
.SH NAME
Azbashenum \- A fast, highly azure pentesting info script.
.SH SYNOPSIS
.B azbashenum
\fI\,func_name --option "value" --option "value"\/\fR
.SH DESCRIPTION
AzBashEnum is a CLI system information enumeration pentesting attack surfaces tool written in BASH. AzBashEnum
enumerates information from your target scope against Microsoft Azure cloud service.
\fB\-\-gen\-man\fR
Generate a manpage for AzBashEnum in your PWD. (Requires GNU help2man)
.SH "REPORTING BUGS"
Report bugs to https://github.com/DFW1N/AzBashEnum/issues