#!/usr/bin/env bash

#####################################################################
#     ___        ____             __    ______                      #
#    /   |____  / __ )____ ______/ /_  / ____/___  __  ______ ___   #
#   / /| /_  / / __  / __ `/ ___/ __ \/ __/ / __ \/ / / / __ `__ \  #
#  / ___ |/ /_/ /_/ / /_/ (__  ) / / / /___/ / / / /_/ / / / / / /  #
# /_/  |_/___/_____/\__,_/____/_/ /_/_____/_/ /_/\__,_/_/ /_/ /_/   #
#                                                                   #
#              Author: Sacha Roussakis-Notter - 2022                #
# ###################################################################

# Copyright (c) 2022 Sacha Roussakis-Notter

################
# BASH COLOURS #
################

nc='\033[0m'
red='\033[0;31m'
green='\033[0;32m'
white='\033[1;37m'
yellow='\033[0;33m'

version=0.0.1

bash_version=${BASH_VERSINFO[0]:-5}

banner() {
cat << "EOF"
#####################################################################
#     ___        ____             __    ______                      #
#    /   |____  / __ )____ ______/ /_  / ____/___  __  ______ ___   #
#   / /| /_  / / __  / __ `/ ___/ __ \/ __/ / __ \/ / / / __ `__ \  #
#  / ___ |/ /_/ /_/ / /_/ (__  ) / / / /___/ / / / /_/ / / / / / /  #
# /_/  |_/___/_____/\__,_/____/_/ /_/_____/_/ /_/\__,_/_/ /_/ /_/   #
#                                                                   #
#              Author: Sacha Roussakis-Notter - 2022                #
#                                                                   #
# ###################################################################
EOF
}

# DETECT INFORMATION

get_os() {
    OS="`uname`"
    case $OS in
    'Linux')
        OS='Linux'
        alias ls='ls --color=auto'
        ;;
    'FreeBSD')
        OS='FreeBSD'
        alias ls='ls -G'
        ;;
    'WindowsNT')
        OS='Windows'
        ;;
    'Darwin') 
        OS='Mac'
        ;;
    'SunOS')
        OS='Solaris'
        ;;
    'AIX') ;;
    *) 
            printf '%s\n' "Unknown OS detected: '$OS', aborting..." >&2
            printf '%s\n' "Open an issue on GitHub to add support for your OS." >&2
            exit 1
        ;;
    esac
}


main() {
    banner
    get_os
}

main